In [4]:
import cv2
import tensorflow.keras
from PIL import Image, ImageOps
import numpy as np

# Capture image from webcam
webcam = cv2.VideoCapture(0)

# Cascade object's face identifier
face_cascade = "haarcascade_frontalface_default.xml"
face_classifier = cv2.CascadeClassifier(face_cascade)

# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = tensorflow.keras.models.load_model('keras_model.h5')

# Define size of target face image
size = (224, 224)

while True:
  # Capture frame-by-frame
  success, image_bgr = webcam.read()
  
  image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
  
  # Convert BGR(cv2) to RGB
  image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)

  # Face detection using Cascade object's face identifier
  faces = face_classifier.detectMultiScale(image_bw)

  for face in faces:
    x, y, w, h = face
    
    # Convert array to image
    cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])

    # Create the array of the right shape to feed into the keras model
    # The 'length' or number of images you can put into the array is
    # determined by the first position in the shape tuple, in this case 1.
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

    # Replace this with the path to your image
    image = cface_rgb
    
    # resize the image to a 224x224 with the same strategy as in TM2:
    # resizing the image to be at least 224x224 and then cropping from the center
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    # turn the image into a numpy array
    image_array = np.asarray(image)

    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

    # Load the image into the array
    data[0] = normalized_image_array

    # run the inference
    prediction = model.predict(data)
    
    # log model prediction [[Masked, Non-Masked]] in 0 - 1 probability
    print(prediction)
    
    if prediction[0][0] > prediction[0][1]:
      cv2.putText(image_bgr,'Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),2)
      cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
    else:
      cv2.putText(image_bgr,'Non-Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),2)
      cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,0,255), 2)

  cv2.imshow("Mask Detection", image_bgr)
  
  # Hit 'q' on the keyboard to quit!
  if cv2.waitKey(1) & 0xFF == ord('q'):
    break

# Release handle to the webcam
webcam.release()
cv2.destroyAllWindows()

[[0.21946234 0.7805377 ]]
[[0.02558196 0.97441804]]
[[0.00026473 0.9997353 ]]
[[0.00043028 0.9995697 ]]
[[0.0001607 0.9998393]]
[[0.00000135 0.9999987 ]]
[[0.00000004 1.        ]]
[[0.00000286 0.99999714]]
[[0. 1.]]
[[0. 1.]]
[[0.00004501 0.99995494]]
[[0.00004501 0.99995494]]
[[0.9990644  0.00093566]]
[[0.9990644  0.00093566]]
[[0.0000856 0.9999144]]
[[0.0000856 0.9999144]]
[[0.00096564 0.9990344 ]]
[[0.00011816 0.99988186]]
[[0.09051333 0.9094867 ]]
[[0.63148206 0.368518  ]]
[[0.99999523 0.00000473]]
[[0.99999523 0.00000473]]
[[0.00002566 0.99997437]]
[[0.00002566 0.99997437]]
[[0.9997131 0.0002868]]
[[0.999998   0.00000205]]
[[0.00408509 0.9959149 ]]
[[0.00408509 0.9959149 ]]
[[0.00255011 0.9974498 ]]
[[0.9999689  0.00003106]]
[[0.9999689  0.00003106]]
[[0.9999906  0.00000944]]
[[0.9999906  0.00000944]]
[[0.9996306  0.00036947]]
[[0.9996306  0.00036947]]
[[0.05873933 0.94126064]]
[[0.9998449  0.00015503]]
[[0.94194406 0.05805593]]
[[1. 0.]]
[[0.9999999  0.00000008]]
[[0.9999999  0.0

[[0.00000046 0.9999995 ]]
[[0.01460185 0.9853982 ]]
[[0.0059331  0.99406683]]
[[0.00206748 0.99793255]]
[[0.0309389  0.96906114]]
[[0.00015349 0.99984646]]
[[0.0000482  0.99995184]]
[[0.00002883 0.99997115]]
[[0.0016845 0.9983156]]
[[0.00941286 0.9905872 ]]
